MagicVilla/MagicVilla_Web/Controllers/VillaController.cs
using AutoMapper;
using MagicVilla_Utility;
using MagicVilla_Web.Models;
using MagicVilla_Web.Models.Dto;
using MagicVilla_Web.Services.IServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Collections.Generic;

namespace MagicVilla_Web.Controllers
{
    public class VillaController : Controller
    {
        private readonly IVillaService _villaService;
        private readonly IMapper _mapper;

        public VillaController(IVillaService villaservice, IMapper mapper)
        {
            _villaService = villaservice;
            _mapper = mapper;
        }

        public async Task<IActionResult> IndexVilla()
        {
            List<VillaDTO> list = new();

            var response = await _villaService.GetAllAsynce<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));
            if (response != null && response.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<VillaDTO>>(Convert.ToString(response.Result));
            }
            return View(list);
        }

        [Authorize(Roles = "admin")]
        public async Task<IActionResult> CreateVilla()
        {
            return View();
        }
        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateVilla(VillaCreateDTO model)
        {
            if (ModelState.IsValid)
            {
                var response = await _villaService.CreateAsync<APIResponse>(model, HttpContext.Session.GetString(SD.SessionToken));
                if (response != null && response.IsSuccess)
                {
                    TempData["success"] = "Villa created Successfully";
                    return RedirectToAction(nameof(IndexVilla));
                }
                TempData["error"] = "Error Encountered.";
            }
            return View(model);
        }

        [Authorize(Roles = "admin")]
        public async Task<IActionResult> UpdateVilla(int villaId)
        {
            var response = await _villaService.GetAsync<APIResponse>(villaId, HttpContext.Session.GetString(SD.SessionToken));
            if (response != null && response.IsSuccess)
            {
                VillaDTO model = JsonConvert.DeserializeObject<VillaDTO>(Convert.ToString(response.Result));
                return View(_mapper.Map<VillaUpdateDTO>(model));
            }
            return NotFound();
        }
        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateVilla(VillaUpdateDTO model)
        {
            if (ModelState.IsValid)
            {
                TempData["success"] = "Villa Updated Successfully";
                var response = await _villaService.UpdateAsync<APIResponse>(model, HttpContext.Session.GetString(SD.SessionToken));
                if (response != null && response.IsSuccess)
                {
                    return RedirectToAction(nameof(IndexVilla));
                }
            }
            TempData["error"] = "Error Encountered.";
            return View(model);
        }
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteVilla(int villaId)
        {
            var response = await _villaService.GetAsync<APIResponse>(villaId, HttpContext.Session.GetString(SD.SessionToken));
            if (response != null && response.IsSuccess)
            {
                VillaDTO model = JsonConvert.DeserializeObject<VillaDTO>(Convert.ToString(response.Result));
                return View(model);
            }
            return NotFound();
        }
        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteVilla(VillaDTO model)
        {


            var response = await _villaService.DeleteAsync<APIResponse>(model.Id, HttpContext.Session.GetString(SD.SessionToken));
            if (response != null && response.IsSuccess)
            {
                TempData["success"] = "Villa Deleted Successfully";
                return RedirectToAction(nameof(IndexVilla));
            }
            TempData["error"] = "Error Encountered.";
            return View(model);
        }
    }
}

MagicVilla/MagicVilla_Web/Views/Villa/CreateVilla.cshtml
@model MagicVilla_Web.Models.Dto.VillaCreateDTO

<form asp-action="CreateVilla">
    <br/>
    <div class="container border p-3">
        <h1 class="text-primary">Create Villa</h1>
        <hr />
        
        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="col-2">
                <label asp-for="Name" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Name" class="form-control"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="Rate" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Rate" class="form-control" />
                <span asp-validation-for="Rate" class="text-danger"></span>
            </div> 

            <div class="col-2">
                <label asp-for="Details" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <textarea asp-for="Details" class="form-control" rows="5" ></textarea> 
                <span asp-validation-for="Details" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="ImageUrl" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="Occupancy" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Occupancy" class="form-control" />
                <span asp-validation-for="Occupancy" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="Sqft" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Sqft" class="form-control" />
                <span asp-validation-for="Sqft" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="Amenity" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <textarea asp-for="Amenity" class="form-control"></textarea>
                <span asp-validation-for="Amenity" class="text-danger"></span>
            </div>
            <div class="col-5 offset-2">
                    <a asp-action="IndexVilla" asp-controller="Villa" class="btn-primary btn form-control">Back to List</a>
            </div>
            <div class="col-5 ">
                <input type="submit" value="Create" class="btn btn-success form-control"/>
            </div>
        </div>
    </div>

</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial"/>
}    

MagicVilla/MagicVilla_Web/Views/Villa/DeleteVilla.cshtml
@model MagicVilla_Web.Models.Dto.VillaDTO

<form asp-action="DeleteVilla">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Delete Villa</h1>
        <hr />

        <input hidden asp-for="Id" />
        <div class="row">
            <div class="col-2">
                <label asp-for="Name" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Name" disabled class="form-control" />
            </div>

            <div class="col-2">
                <label asp-for="Rate" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Rate" disabled class="form-control" />
            </div>

            <div class="col-2">
                <label asp-for="Details" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <textarea asp-for="Details" disabled class="form-control" rows="5"></textarea>
            </div>

            <div class="col-2">
                <label asp-for="ImageUrl" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="ImageUrl" disabled class="form-control" />
            </div>

            <div class="col-2">
                <label asp-for="Occupancy" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Occupancy" disabled class="form-control" />
            </div>

            <div class="col-2">
                <label asp-for="Sqft" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Sqft" disabled class="form-control" />
            </div>

            <div class="col-2">
                <label asp-for="Amenity" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <textarea asp-for="Amenity" disabled class="form-control"></textarea>
            </div>
            <div class="col-5 offset-2">
                <a asp-action="IndexVilla" asp-controller="Villa" class="btn-primary btn form-control">Back to List</a>
            </div>
            <div class="col-5 offset-bg-opacity-25">
                <input type="submit" value="Delete" class="btn btn-danger form-control" />
            </div>
        </div>
    </div>

</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}    

MagicVilla/MagicVilla_Web/Views/Villa/IndexVilla.cshtml
@model IEnumerable<MagicVilla_Web.Models.Dto.VillaDTO>
<br />
<div class="container p-4 border">
    <div class="row pb-2">
        <div class="col">
            <h1 class="text-primary">Villa List</h1>
        </div>
        <div class="col text-end pt-1">
            <a asp-controller="Villa" asp-action="CreateVilla" class="btn btn-outline-primary"><i class="bi bi-plus-square-fill"></i> Create New Villa</a>

        </div>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Occupancy 
                </th>
                <th>
                    Price
                </th>
                <th>

                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Name</td>
                    <td>@item.Occupancy</td>
                    <td>@((item.Rate).ToString("c"))</td>
                    <td>
                        <a asp-controller="Villa" asp-action="UpdateVilla" asp-route-villaId="@item.Id" class="btn btn-success"><i class="bi bi-pencil-square"></i></a>
                        <a asp-controller="Villa" asp-action="DeleteVilla" asp-route-villaId="@item.Id" class="btn btn-danger"><i class="bi bi-trash-fill"></i></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

MagicVilla/MagicVilla_Web/Views/Villa/UpdateVilla.cshtml
@model MagicVilla_Web.Models.Dto.VillaUpdateDTO

<form asp-action="UpdateVilla">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Update Villa</h1>
        <hr />

        <input hidden asp-for="Id"/>
        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="col-2">
                <label asp-for="Name" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="Rate" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Rate" class="form-control" />
                <span asp-validation-for="Rate" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="Details" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <textarea asp-for="Details" class="form-control" rows="5"></textarea>
                <span asp-validation-for="Details" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="ImageUrl" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="Occupancy" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Occupancy" class="form-control" />
                <span asp-validation-for="Occupancy" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="Sqft" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Sqft" class="form-control" />
                <span asp-validation-for="Sqft" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="Amenity" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <textarea asp-for="Amenity" class="form-control"></textarea>
                <span asp-validation-for="Amenity" class="text-danger"></span>
            </div>
            <div class="col-5 offset-2">
                <a asp-action="IndexVilla" asp-controller="Villa" class="btn-primary btn form-control">Back to List</a>
            </div>
            <div class="col-5 offset-bg-opacity-25">
                <input type="submit" value="Update" class="btn btn-success form-control" />
            </div>
        </div>
    </div>

</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}    